### ISSUE TITLE
Filtering on letter `Q` kills the process

### ISSUE THREAD

**Issue by leereilly** [arraypad/emojifinder#2]
Found that any time I filter on / press <kbd>Q</kbd> then it will escape back to the command prompt. 
See me attempt to search for `squirrel` at 12 secs below:

https://user-images.githubusercontent.com/121322/167508376-cc92f384-4c41-45d6-b142-c1f0e49d1eb6.mp4

On macOS 11.5.1 using both latest Hyper and Terminal app if that's helpful 😎

**Comment by arraypad** [comment]
Thanks very much for taking the time to report this, and sorry for the slow response.

I've just published 0.2.2 which should fix this. Please don't hesitate to let me know if you run into any other issues.
